### ISSUE TITLE
Internal error, an invalid response was received from the ad server

### ISSUE THREAD

**Issue by victoorlucas** [sbugert/react-native-admob#255]
Since yesterday this error occurs for me. I tried the proposed solutions from the issue #220 but I don't get it solved.

My code:
 `<AdMobBanner
          adSize="mediumRectangle"
          adUnitID="my ad unit id"
          testDevices={[AdMobBanner.simulatorId]}
          onAdFailedToLoad={error => console.error(error)}
        />`

The error: 

> Internal error, an invalid response was received from the ad server.
> handleAdFailedToLoad
>     C:\Users\victo\Desktop\app1\node_modules\react-native-admob\RNAdMobBanner.js:45:59
> proxiedMethod
>     C:\Users\victo\Desktop\app1\node_modules\react-proxy\modules\createPrototypeProxy.js:44:35
> _invokeGuardedCallback
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:73:23
> invokeGuardedCallback
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:47:40
> invokeGuardedCallbackAndCatchFirstError
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:50:60
> executeDispatch
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:125:132
> executeDispatchesInOrder
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:130:283
> executeDispatchesAndRelease
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3255:62
> executeDispatchesAndReleaseTopLevel
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3259:43
> forEachAccumulated
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3252:69
> processEventQueue
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3309:147
> runEventQueueInBatch
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3535:83
> handleTopLevel
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3539:33
> <unknown>
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3560:55
> batchedUpdates
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:2754:26
> batchedUpdates
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:202:35
> batchedUpdatesWithControlledComponents
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:209:34
> _receiveRootNodeIDEvent
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3559:50
> receiveEvent
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\Renderer\ReactNativeFiber-dev.js:3564:60
> __callFunction
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:299:47
> <unknown>
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26
> __guard
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:262:6
> callFunctionReturnFlushedQueue
>     C:\Users\victo\Desktop\app1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17

Someone have a soluction for this? Thanks.

**Comment by hyorax** [comment]
I'm tired of saying this, I have the same problem!

**Comment by victoorlucas** [comment]
I still have the problem.

**Comment by hyorax** [comment]
my problem is still going on, have you found a @victoorlucas solution?

**Comment by r0hit-gupta** [comment]
I too have the same problem. Can someone please help us out?

**Comment by hyorax** [comment]
Resolved when you approve the error on the AdMob homepage!

**Comment by r0hit-gupta** [comment]
@hyorax can you please explain that in detail or provide a link?

**Comment by hyorax** [comment]
1)Click Home page,

> Your ad units are not displaying ads because you haven't provided your account payments information yet. 

2)Click Fix It.
3)Click Select Payment,
4)And Submit.
Finish, solved for me!

**Comment by r0hit-gupta** [comment]
I am glad you have finally solved the issue. However, there is no such warning on my account. Gotta find some other solution.

**Comment by victoorlucas** [comment]
Glad that these solution worked for you @hyorax, but I still get the error.

**Comment by muzammil-triffort** [comment]
Guys, Any fixes??

**Comment by r0hit-gupta** [comment]
I created a new react native project and relinked the libraries. Everything worked after.

**Comment by matheusrocha89** [comment]
I am having the same problem @r0hit-gupta @victoorlucas did you find a solution?

**Comment by r0hit-gupta** [comment]
@matheusrocha89 I created a new project from scratch. Installed admob and linked it. Then copy pasted the react code from my original project. I also created a new Ad Unit on Admob and used a real device to test the ads. Ads were not showing on the emulator for some reason.

**Comment by matheusrocha89** [comment]
I am trying on a real device and still getting this error on my console when I activate the debug mode on react native. When you were testing you used the release version or the test version of your app @r0hit-gupta ?

**Comment by matheusrocha89** [comment]
@hyorax After you confirm your informations took some time to start to work?

**Comment by matheusrocha89** [comment]
@r0hit-gupta after I confirm my informations took some minutes to start to work. Now The error is `The ad request was successful, but no ad was returned due to lack of ad inventory.` I guess I need to configure something on my AdMOB to put some ads on my inventory, I am not sure, I will make some research about that

**Comment by r0hit-gupta** [comment]
@matheusrocha89 try changing the banner size.

**Comment by matheusrocha89** [comment]
I am using `AdMobInterstitial` don't have size.

**Comment by r0hit-gupta** [comment]
@matheusrocha89 I suggest you wait for some more time. It usually takes some time for new ad units to show up.

**Comment by matheusrocha89** [comment]
I guess could be that too, BTW I will keep this issue updated If I have some success. Thanks for the help @r0hit-gupta

**Comment by ayushnawani** [comment]
@matheusrocha89 I am also getting this error  "The ad request was successful, but no ad was returned due to lack of ad inventory.". How did you solve it?

**Comment by matheusrocha89** [comment]
I just waited a little bit so the afs started to appear, just that

**Comment by hyorax** [comment]
Try this:

```
<AdMobBanner
     adSize="smartBannerPortrait"
     adUnitID="ca-app-pub-xxx/xxx"
     testDevices={[AdMobBanner.simulatorId]}
 />
```

**Comment by bhargav82** [comment]
I had the same issue with my app. first day I will try with my AdMob account its say "Internal error, an invalid response was received from the ad server." on next day try with run-android it's working fine for me. please wait for some time max 1 day after the create AdMob banner add after it's work.

**Comment by ayushnawani** [comment]
thanks, guys, I waited for 1 day and now ads are showing for me.

**Comment by myrsapp** [comment]
> thanks, guys. I waited for 1 day and now ads are showing for me.

I created the ad unit 1 week ago, still I got nothing. Any solution?

**Comment by andretimm** [comment]
I have the same problem, I have created the ads for 3 days, and continue with the error.

**Comment by myrsapp** [comment]
Mine is already shown. Make sure your payment detail is filled. Admob will give you an email that your email has been verified but Admob wont tell you when your ads units are ready. You can check your ads unit on your test device

**Comment by andretimm** [comment]
I have already set up my payment details when I created the account. On the homepage it appears that everything is right. But I keep getting the error.

![image](https://user-images.githubusercontent.com/8572757/46292838-4766f300-c568-11e8-94b0-bc0ec50acc7e.png)

**Comment by matheusrocha89** [comment]
Wai a little bit more, if everything is correct, you have all the requirements just wait and the ads will start to appear.
